name: "Run all tests"
on:
  push:
    paths:
      - "**.rs"
  pull_request:
    paths:
      - "**.rs"

jobs:
  run-tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "install latest stable Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"
          override: true
      - uses: "Swatinem/rust-cache@v1"
        with:
          key: "test"
      - name: "run tests"
        run: "cargo test"
